name: Test Kafka

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Kafka
    runs-on: ubuntu-latest
    services:
      kafka:
        image: bitnami/kafka:3.9.0
        env:
          # Enable KRaft mode
          KAFKA_ENABLE_KRAFT: 'yes'
          KAFKA_CFG_PROCESS_ROLES: broker,controller
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@127.0.0.1:9093'

          # Listeners
          KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
          KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka:9094'
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

          # Additional settings
          KAFKA_BROKER_ID: '1'
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
          KAFKA_CFG_NUM_PARTITIONS: '2'
          ALLOW_PLAINTEXT_LISTENER: 'yes'
          BITNAMI_DEBUG: 'yes'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for Kafka
        uses: ./
        with:
          type: kafka
          host: kafka
          port: 9092
          timeout: 300

  test-timeout:
    name: Test Kafka - Timeout
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for Kafka
        id: wait-for-kafka
        uses: ./
        continue-on-error: true
        with:
          type: kafka
          host: kafka
          port: 9092
          timeout: 30

      - name: Fail if wait succeeded unexpectedly
        if: steps.wait-for-kafka.outcome != 'failure'
        run: exit 1
