name: Test NATS

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test NATS
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.11.8
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for NATS
        uses: ./
        with:
          type: nats
          host: nats
          port: 4222
          timeout: 300

  test-timeout:
    name: Test NATS - Timeout
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Patch action.yml
        run: |
          sed -i 's|image:\s.*|image: Dockerfile|g' action.yml

      - name: Wait for NATS
        id: wait-for-nats
        uses: ./
        continue-on-error: true
        with:
          type: nats
          host: nats
          port: 4222
          timeout: 30

      - name: Fail if wait succeeded unexpectedly
        if: steps.wait-for-nats.outcome != 'failure'
        run: exit 1
